import type { CatalogPackage } from "@/lib/content/schema";

import { contractMonths, pkg, t } from "./helpers";

const mbps = (value: number) => ({ value, unit: "Mbps" as const });
const gbps = (value: number) => ({ value, unit: "Gbps" as const });

const newCustomerFile = "home/WifiHome.data.ts";
const vatExcludedNote = "เว็บเดิมแสดง “(ไม่รวมภาษี)” ทุกแพ็กเกจลูกค้าใหม่";

// New customers: the cards shown on /broadband and the home page (dataWifiHome).
export const broadbandNew: CatalogPackage[] = [
  pkg({
    id: "fiber-500-499",
    category: "broadband-new",
    group: "new-customer",
    name: t("แพ็กเกจเน็ตบ้านสุดคุ้ม", "Great-value home internet"),
    speed: { download: mbps(500), upload: mbps(500) },
    contract: contractMonths(24),
    price: { amount: 499, per: "month", vat: "excluded" },
    benefits: ["trueid-tv-box", "camera-indoor", "sim-10gb", "wifi-tower"],
    conditions: [t("เลือกสิทธิประโยชน์ได้ 1 อย่าง", "Choose one of the benefits")],
    from: [newCustomerFile, "dataWifiHome id 1"],
    notes: [
      vatExcludedNote,
      "ชื่อเดิม “แพ็คเกจเน็ตบ้านสุดค้ม!!!” แก้คำสะกดเป็น “สุดคุ้ม”",
      "เว็บเดิมมีข้อความ “ระยะสัญญา 12 เดือน” ในช่องโปรโมชัน ขัดกับสัญญา 24 เดือน จึงยังไม่แสดง",
    ],
  }),
  pkg({
    id: "fiber-700-599",
    category: "broadband-new",
    group: "new-customer",
    name: t("แพ็กเกจสุดคุ้ม", "Great-value package"),
    speed: { download: mbps(700), upload: mbps(700) },
    contract: contractMonths(24),
    price: { amount: 599, per: "month", vat: "excluded" },
    benefits: ["wifi-router", "wifi-tower", "trueid-tv-box", "truevisions-now-joy", "iqiyi-24m", "sim-10gb", "viu-24m"],
    from: [newCustomerFile, "dataWifiHome id 2"],
    notes: [vatExcludedNote, "ชื่อเดิม “แพ็คเกจสุดค้ม” แก้คำสะกด"],
  }),
  pkg({
    id: "fiber-500-600-cctv",
    category: "broadband-new",
    group: "new-customer",
    name: t("แพ็กเกจฟรีประกันภัยและกล้องวงจรปิด", "Free insurance and security camera"),
    speed: { download: mbps(500), upload: mbps(500) },
    contract: contractMonths(24),
    price: { amount: 600, per: "month", vat: "excluded" },
    benefits: ["wifi-router", "camera-indoor", "sim-10gb", "dhipaya-insurance", "fwd-insurance", "truevisions-now-joy"],
    from: [newCustomerFile, "dataWifiHome id 3"],
    notes: [vatExcludedNote],
  }),
  pkg({
    id: "fiber-500-650-cctv",
    category: "broadband-new",
    group: "new-customer",
    name: t(
      "แพ็กเกจฟรีประกันภัยและกล้องวงจรปิดใน-นอกบ้าน",
      "Free insurance with indoor and outdoor cameras",
    ),
    speed: { download: mbps(500), upload: mbps(500) },
    contract: contractMonths(24),
    price: { amount: 650, per: "month", vat: "excluded" },
    benefits: [
      "wifi-router",
      "camera-indoor",
      "camera-outdoor",
      "sim-10gb",
      "dhipaya-insurance",
      "fwd-insurance",
      "truevisions-now-joy",
    ],
    from: [newCustomerFile, "dataWifiHome id 4"],
    notes: [vatExcludedNote],
  }),
  pkg({
    id: "fiber-1g-799",
    category: "broadband-new",
    group: "new-customer",
    name: t("ใหม่! Streaming, Gaming, Working PRO AI 1Gbps", "New! Streaming, Gaming, Working PRO AI 1 Gbps"),
    speed: { download: gbps(1), upload: gbps(1) },
    contract: contractMonths(24),
    price: { amount: 799, per: "month", vat: "excluded" },
    benefits: ["wifi-router-pair", "sim-20gb", "camera-indoor", "gaming-nation", "truevisions-now-joy", "viu-24m"],
    from: [newCustomerFile, "dataWifiHome id 5"],
    notes: [
      vatExcludedNote,
      "ชื่อเดิม “ใหม่! PStreaming, Gaming, WorkingRO AI 1Gbps” สะกดเพี้ยน แก้เป็น “Streaming, Gaming, Working PRO AI” รอยืนยันชื่อทางการ",
    ],
  }),
  pkg({
    id: "fiber-500-999-netflix",
    category: "broadband-new",
    group: "new-customer",
    name: t("TrueOnline Super Netflix Premium", "TrueOnline Super Netflix Premium"),
    speed: { download: mbps(500), upload: mbps(500) },
    contract: contractMonths(24),
    price: { amount: 999, per: "month", vat: "excluded" },
    benefits: ["wifi-router", "trueid-tv-box", "netflix", "truevisions-now-joy", "sim-10gb"],
    from: [newCustomerFile, "dataWifiHome id 6 (รายการแรกที่ใช้ id 6)"],
    notes: [vatExcludedNote],
  }),
  pkg({
    id: "fiber-1500-1199",
    category: "broadband-new",
    group: "new-customer",
    name: t("TrueOnline Super Netflix Premium 1.5Gbps", "TrueOnline Super Netflix Premium 1.5 Gbps"),
    speed: { download: gbps(1.5), upload: gbps(1.5) },
    contract: contractMonths(24),
    price: { amount: 1199, per: "month", vat: "excluded" },
    benefits: [
      "wifi-router",
      "wifi-tower",
      "trueid-tv-box",
      "sim-20gb",
      "camera-indoor",
      "viu-24m",
      "gaming-partner",
      "ihavecpu",
      "gaming-nation",
    ],
    from: [newCustomerFile, "dataWifiHome id 6 (รายการที่สองที่ใช้ id 6)"],
    notes: [
      vatExcludedNote,
      "เว็บเดิมใช้ชื่อเดียวกับแพ็กเกจ 999 บาท แต่ไอคอนสิทธิประโยชน์ไม่มี Netflix และเน้นเกม จึงเติม “1.5Gbps” ท้ายชื่อเพื่อแยก รอยืนยันชื่อจริง",
      "ไอคอนสีแดงรูปวงวน (image 354.png) ระบุชื่อพันธมิตรไม่ได้ ใช้ป้าย “พันธมิตรด้านเกม” ไปก่อน",
    ],
  }),
];

const existingFile = "Boardband/Boardband-old.data.ts";
const existingAudience = t("ลูกค้าปัจจุบันที่ใช้แพ็กเกจ 599 บาทขึ้นไป", "Current customers on a 599-baht package or higher");
const noVatNote = "เว็บเดิมไม่ระบุว่ารวม VAT หรือไม่";

// Existing customers: speed boosts and add-ons on /broadband-old.
export const broadbandExisting: CatalogPackage[] = [
  pkg({
    id: "boost-1000-1000",
    category: "broadband-existing",
    group: "speed-boost",
    name: t("แพ็กเกจเพิ่มสปีด 1000/1000 Mbps", "Speed boost to 1000/1000 Mbps"),
    audience: existingAudience,
    speed: { download: mbps(1000), upload: mbps(1000) },
    price: { amount: 199, per: "month", vat: "unknown" },
    from: [existingFile, "PackageMonthy id 1"],
    notes: [noVatNote],
  }),
  pkg({
    id: "boost-1000-500",
    category: "broadband-existing",
    group: "speed-boost",
    name: t("แพ็กเกจเพิ่มสปีด 1000/500 Mbps", "Speed boost to 1000/500 Mbps"),
    audience: existingAudience,
    speed: { download: mbps(1000), upload: mbps(500) },
    price: { amount: 99, per: "month", vat: "unknown" },
    from: [existingFile, "PackageMonthy id 2"],
    notes: [noVatNote],
  }),
  pkg({
    id: "boost-500-500",
    category: "broadband-existing",
    group: "speed-boost",
    name: t("แพ็กเกจเพิ่มสปีด 500/500 Mbps", "Speed boost to 500/500 Mbps"),
    audience: existingAudience,
    speed: { download: mbps(500), upload: mbps(500) },
    price: { amount: 89, per: "month", vat: "unknown" },
    from: [existingFile, "PackageMonthy id 3"],
    notes: [noVatNote],
  }),
  pkg({
    id: "boost-1000-500-gamepack",
    category: "broadband-existing",
    group: "speed-boost",
    name: t("แพ็กเกจเพิ่มสปีด 1000/500 Mbps (GamePack)", "Speed boost to 1000/500 Mbps (GamePack)"),
    audience: existingAudience,
    speed: { download: mbps(1000), upload: mbps(500) },
    price: { amount: 159, per: "month", vat: "unknown" },
    details: [
      t(
        "แบ่งเป็น 2 ช่องทาง: สำหรับเกม 700/300 Mbps และการใช้งานอื่น 300/200 Mbps",
        "Split into two lanes: 700/300 Mbps for gaming and 300/200 Mbps for everything else",
      ),
    ],
    from: [existingFile, "PackageMonthy id 4"],
    notes: [noVatNote, "ถอดข้อความเดิม “แบ่ง 2 ท่อ flexi Gamer : 700/300Mbps Other : 300/200 Mbps” เป็นประโยค"],
  }),
  pkg({
    id: "boost-1000-500-duplicate",
    category: "broadband-existing",
    group: "speed-boost",
    name: t("แพ็กเกจเพิ่มสปีด 1000/500 Mbps", "Speed boost to 1000/500 Mbps"),
    audience: existingAudience,
    speed: { download: mbps(1000), upload: mbps(500) },
    price: { amount: 99, per: "month", vat: "unknown" },
    from: [existingFile, "PackageMonthy id 5"],
    hide: "ซ้ำกับ PackageMonthy id 2 ทุกช่อง",
  }),
  pkg({
    id: "boost-1000-1000-daily",
    category: "broadband-existing",
    group: "speed-boost-daily",
    name: t("แพ็กเกจเพิ่มสปีด 1000/1000 Mbps รายวัน", "Daily speed boost to 1000/1000 Mbps"),
    speed: { download: mbps(1000), upload: mbps(1000) },
    price: { amount: 199, per: "package", vat: "unknown" },
    from: [existingFile, "PackageDaily id 1–2"],
    hide: "แท็บ “รายวัน” มี 2 รายการที่เหมือนกันและราคาเท่าแพ็กรายเดือน 199 บาท ไม่มีระยะเวลา น่าจะเป็นข้อมูลตัวอย่าง รอข้อมูลแพ็กรายวันจริง",
  }),
  pkg({
    id: "addon-cctv",
    category: "broadband-existing",
    group: "add-ons",
    name: t("กล้องวงจรปิด CCTV", "CCTV security camera"),
    audience: t("ลูกค้าทรูออนไลน์", "True Online customers"),
    contract: contractMonths(18),
    price: { amount: 99, per: "month", vat: "unknown" },
    details: [t("ดูย้อนหลังได้ 7 วัน", "Watch recordings from the past 7 days"), t("มีประกัน", "Warranty included")],
    image: "cctv-offer",
    from: [existingFile, "PackgeCCTV id 1"],
    notes: [
      noVatNote,
      "PackgeCCTV id 2 ซ้ำกับรายการนี้แต่ไม่มีคำว่า “มีประกัน” จึงรวมเป็นรายการเดียว รอยืนยันว่ามีประกันหรือไม่",
    ],
  }),
  pkg({
    id: "addon-trueid-tv",
    category: "broadband-existing",
    group: "add-ons",
    name: t("TrueID TV + แพ็กเกจ TrueID", "TrueID TV + TrueID package"),
    audience: t("ลูกค้าทรูออนไลน์", "True Online customers"),
    price: { amount: 99, per: "month", vat: "unknown" },
    image: "trueid-tv-offer",
    from: [existingFile, "PackgeTrueIDTV id 1"],
    notes: [
      noVatNote,
      "ข้อความเดิม “TOL get free OTT Onlineiservice TrueIDTV 99 baht” อ่านไม่เข้าใจ จึงยังไม่แสดง รอข้อความเงื่อนไขที่ถูกต้อง",
    ],
  }),
];
